package logiled.Controllers;

public enum  LoCodepage {
        l_game ((byte) 0x2),
        l_caps ((byte) 0x3),
        k_a ((byte) 0x4),
        k_b ((byte) 0x5),
        k_c ((byte) 0x6),
        k_d ((byte) 0x7),
        k_e ((byte) 0x8),
        k_f ((byte) 0x9),
        k_g ((byte) 0xA),
        k_h ((byte) 0xB),
        k_i ((byte) 0xC),
        k_j ((byte) 0xD),
        k_k ((byte) 0xE),
        k_l ((byte) 0xF),
        k_m ((byte) 0x10),
        k_n ((byte) 0x11),
        k_o ((byte) 0x12),
        k_p ((byte) 0x13),
        k_q ((byte) 0x14),
        k_r ((byte) 0x15),
        k_s ((byte) 0x16),
        k_t ((byte) 0x17),
        k_u ((byte) 0x18),
        k_v ((byte) 0x19),
        k_w ((byte) 0x1A),
        k_x ((byte) 0x1B),
        k_y ((byte) 0x1C),
        k_z ((byte) 0x1D),
        k_1 ((byte) 0x1E),
        k_2 ((byte) 0x1F),
        k_3 ((byte) 0x20),
        k_4 ((byte) 0x21),
        k_5 ((byte) 0x22),
        k_6 ((byte) 0x23),
        k_7 ((byte) 0x24),
        k_8 ((byte) 0x25),
        k_9 ((byte) 0x26),
        k_0 ((byte) 0x27),
        k_enter ((byte) 0x28),
        k_esc ((byte) 0x29),
        k_backspace ((byte) 0x2a),
        k_tab ((byte) 0x2b),
        k_space ((byte) 0x2c),
        k_dash ((byte) 0x2d),
        k_equal ((byte) 0x2e),
        k_bracket_open ((byte) 0x2f),
        k_bracket_close ((byte) 0x30),
        k_backslash ((byte) 0x32),
        k_semicolon ((byte) 0x33),
        k_quotation ((byte) 0x34),
        k_tilde ((byte) 0x35),
        k_comma ((byte) 0x36),
        k_dot ((byte) 0x37),
        k_shash ((byte) 0x38),
        k_caps ((byte) 0x39),
        k_f1 ((byte) 0x3a),
        k_f2 ((byte) 0x3b),
        k_f3 ((byte) 0x3c),
        k_f4 ((byte) 0x3d),
        k_f5 ((byte) 0x3e),
        k_f6 ((byte) 0x3f),
        k_f7 ((byte) 0x40),
        k_f8 ((byte) 0x41),
        k_f9 ((byte) 0x42),
        k_f10 ((byte) 0x43),
        k_f11 ((byte) 0x44),
        k_f12 ((byte) 0x45),
        k_prtscr ((byte) 0x46),
        k_scrl ((byte) 0x47),
        k_pause ((byte) 0x48),
        k_ins ((byte) 0x49),
        k_home ((byte) 0x4a),
        k_pg_up ((byte) 0x4b),
        k_del ((byte) 0x4c),
        k_end ((byte) 0x4d),
        k_pg_dn ((byte) 0x4e),
        k_arr_right ((byte) 0x4f),
        k_arr_left ((byte) 0x50),
        k_arr_down ((byte) 0x51),
        k_arr_up ((byte) 0x52),
        k_num ((byte) 0x53),
        k_num_slash ((byte) 0x54),
        k_num_asterisk ((byte) 0x55),
        k_num_minus ((byte) 0x56),
        k_num_plus ((byte) 0x57),
        k_num_enter ((byte) 0x58),
        k_num_1 ((byte) 0x59),
        k_num_2 ((byte) 0x5a),
        k_num_3 ((byte) 0x5b),
        k_num_4 ((byte) 0x5c),
        k_num_5 ((byte) 0x5d),
        k_num_6 ((byte) 0x5e),
        k_num_7 ((byte) 0x5f),
        k_num_8 ((byte) 0x60),
        k_num_9 ((byte) 0x61),
        k_num_0 ((byte) 0x62),
        k_num_period ((byte) 0x63),
        k_menu ((byte) 0x65),
        k_l_ctrl ((byte) 0xe0),
        k_l_shift ((byte) 0xe1),
        k_l_alt ((byte) 0xe2),
        k_win ((byte) 0xe3),
        k_r_ctrl ((byte) 0xe4),
        k_r_shift ((byte) 0xe5),
        k_r_alt ((byte) 0xe6),
        k_fn ((byte) 0xe7);

    private final byte value;

    LoCodepage(byte value){
        this.value = value;
    }

    public byte getValue() { return value; }
}
